language: generic
os:
- linux
- osx
osx_image: xcode6.4
dist: trusty
sudo: false

env:
  - MPLBACKEND='Agg' OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 NUMEXPR_NUM_THREADS=1 HAL_TEST_DATA=${TRAVIS_BUILD_DIR}/hawc_hal/tests/data PATH="${HOME}/miniconda/bin:${PATH}"

cache:
  directories:
    - $HOME/download
    - $HOME/miniconda
  timeout: 1000

before_cache:
  - if ! [[ $TRAVIS_TAG ]]; then rm -rf $HOME/miniconda/conda-bld; fi
  - conda clean -y -a
  - rm -rf $HOME/miniconda/locks $HOME/miniconda/pkgs $HOME/miniconda/var $HOME/miniconda/conda-meta/history


before_install:
  - echo "listing home"
  - ls $HOME
  - echo "end of listing"
  - |

        if [ ! -d "$HOME/miniconda/envs/test-environment" ]; then

            rm -rf $HOME/miniconda

            # Rebuilding the cache

            echo "########################################"
            echo "INSTALLATION CACHE NOT FOUND. REBUILDING"
            echo "########################################"

            # Install Miniconda appropriate for the system (Mac or Linux)

            if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then

                wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh

            else

              wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh

            fi

            # Install miniconda and all the packages

            bash miniconda.sh -b -p $HOME/miniconda
            hash -r
            conda config --set always_yes yes --set changeps1 no
            conda update -q conda
            conda create -q -n test-environment -c conda-forge -c threeml python=2.7 root5 numba numpy scipy astropy healpy threeml

        else

            # Using cache

            echo "##################################"
            echo "INSTALLATION CACHE FOUND. REUSING"
            echo "##################################"

        fi

install:
  - conda config --set always_yes yes --set changeps1 no
  - conda info -a
  - source activate test-environment
  - hash -r
  - conda update -c conda-forge -c threeml threeml astromodels
  - conda install -c conda-forge pytest-cov codecov
  - pip install root_numpy
  - pip install .

script:
  - python -m pytest -vv --cov=hawc_hal
  - conda clean -y -a
  - pip uninstall hawc_hal -y

after_success:
  - codecov