language: generic

os:
    - linux
    - osx
osx_image: xcode6.4

cache:

  directories:

    - $HOME/miniconda

before_cache:

  - conda clean -y -a
  - pip uninstall hawc_hal -y

install:
  - echo "listing home"
  - ls $HOME
  - echo "end of listing"
  - |

        if [ ! -d "$HOME/miniconda/envs/test-environment" ]; then

            rm -rf $HOME/miniconda

            # Rebuilding the cache

            echo "########################################"
            echo "INSTALLATION CACHE NOT FOUND. REBUILDING"
            echo "########################################"

            # Install Miniconda appropriate for the system (Mac or Linux)

            if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then

                wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh

            else

              wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh

            fi

            # Install miniconda and all the packages

            bash miniconda.sh -b -p $HOME/miniconda
            export PATH="$HOME/miniconda/bin:$PATH"
            hash -r
            conda config --set always_yes yes --set changeps1 no
            conda update -q conda
            conda create -q -n test-environment -c conda-forge -c threeml python=2.7 root5 numba numpy scipy astropy healpy threeml
            source activate test-environment
            pip install root_numpy

        else

            # Using cache

            echo "##################################"
            echo "INSTALLATION CACHE FOUND. REUSING"
            echo "##################################"

            export PATH="$HOME/miniconda/bin:$PATH"
            source activate test-environment
            conda update -c conda-forge -c threeml threeml astromodels

        fi

  - conda info -a
  - pip install .

script:
  - export MPLBACKEND='Agg'
  - export OMP_NUM_THREADS=1
  - export MKL_NUM_THREADS=1
  - export NUMEXPR_NUM_THREADS=1
  - export HAL_TEST_DATA=$TRAVIS_BUILD_DIR/hawc_hal/tests/data
  - pytest -vv
